---
title: "Data visializations using R: Homework"
subtitle: "HEV9009 Scientific Communication, Collaboration and Design in Quantitative Research Using R"
format:
  typst:
    margin:
      left: 5cm
      right: 5cm
      y: 3cm
---
Your homework should result in multiple versions of a standalone graphic in PDF format. The size of the graphic should be adjusted to a suitable format.[^format] Create at least three versions of the same using the same underlying data, using different design choices. The various design choices should be carefully considered and support the interpretation of the graphics. The distinct design choices could include organization of the underlying data, different facets, manipulation of axes, annotations, color schemes, titles, scales, etc.
Be sure to include a caption in the figure file to make it completely standalone.

For this homework, you can use data from your own work, data you find online, or as part of an R package. The `exscidata` package contains datasets used in examples in this course. Other great resources are [Awesom Public Datasets](https://github.com/awesomedata/awesome-public-datasets), or the [datasets package](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html).

Be prepared to share your graphics at our next meeting and discuss your design choices and the message your graphic conveys.


[^format]: E.g., a large infographic-style graphic could be larger than A4. A graphic designated for publication in a scientific journal could be in a two-column width and 1/3 of a printed page; consult your favorite scientific journal. 